# numpy:package for multidimensional



In [7]:
import numpy as np

In [8]:
simple_list=[3,5,6]
np.array(simple_list)

array([3, 5, 6])

In [9]:
arr=np.array([1,3,4])
arr

array([1, 3, 4])

In [10]:
np.arange(5,150)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
       148, 149])

In [11]:
np.arange(5,150,2)

array([  5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,  29,
        31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
        57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,
        83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105, 107,
       109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133,
       135, 137, 139, 141, 143, 145, 147, 149])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [15]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.linspace(0,1,5)             ##nomal distribution 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.linspace(0,20,8) 

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [26]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
np.random.rand(3,5)

array([[0.8439602 , 0.39010662, 0.68367273, 0.52168586, 0.23768781],
       [0.07580531, 0.15444815, 0.45028827, 0.44324243, 0.99277788],
       [0.17736003, 0.39069717, 0.94676755, 0.18011762, 0.11820155]])

In [28]:
arr=np.random.randn(2,4)
arr

array([[ 0.57786419, -0.85416229, -0.16922132, -0.87747202],
       [-1.72145275, -0.75997004,  0.20479552, -0.30572776]])

In [37]:
np.random.randint(2,10)

2

In [30]:
np.random.randint(20,56,100) ##uniform distribution

array([28, 38, 39, 48, 38, 47, 22, 44, 51, 23, 47, 38, 24, 20, 37, 54, 49,
       25, 37, 46, 37, 28, 32, 55, 30, 46, 37, 55, 44, 29, 46, 31, 23, 46,
       31, 20, 53, 20, 22, 28, 31, 31, 36, 23, 48, 30, 41, 42, 40, 53, 36,
       40, 42, 29, 30, 34, 35, 44, 37, 41, 38, 40, 52, 40, 54, 25, 39, 20,
       41, 26, 22, 49, 37, 44, 38, 31, 45, 49, 53, 22, 36, 39, 29, 42, 36,
       31, 40, 46, 20, 45, 55, 35, 44, 22, 50, 44, 40, 49, 30, 43])

In [38]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [43]:
rand_array=np.random.randint(0,100,50)
rand_array

array([ 8, 92, 78, 63, 56,  7, 75, 86, 36, 16,  4,  9, 75, 80,  8, 74, 44,
       18, 48, 74,  5, 86, 10,  9, 31, 68, 92, 92, 88, 92, 48, 12, 96, 66,
       73, 94, 98, 98, 93, 75, 33, 16,  3, 89, 58, 84, 85, 66, 15, 59])

In [44]:
sample_array.reshape(5,9)   cannot reshape because 5*9=45 which is greater than 30

ValueError: cannot reshape array of size 30 into shape (5,9)

In [45]:
rand_array.min()

3

In [46]:
rand_array.argmin()

42

In [47]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [49]:
rand_array.max()

98

In [51]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
a=np.random.rand(2,4)
a

array([[0.57345777, 0.47407317, 0.56746468, 0.99461935],
       [0.97108665, 0.90391952, 0.53106922, 0.04657247]])

In [55]:
a.T

array([[0.57345777, 0.97108665],
       [0.47407317, 0.90391952],
       [0.56746468, 0.53106922],
       [0.99461935, 0.04657247]])

In [58]:
sample_array=np.arange(10,20)
sample_array  

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
sample_array [8] 

18

In [60]:
sample_array  [2:5]

array([12, 13, 14])

In [62]:
sample_array  [1:7]=200
sample_array  

array([ 10, 200, 200, 200, 200, 200, 200,  17,  18,  19])

In [63]:
sample_array  [0:7]

array([ 10, 200, 200, 200, 200, 200, 200])

In [64]:
subset_sample_array = sample_array [0:7]
subset_sample_array  

array([ 10, 200, 200, 200, 200, 200, 200])

In [65]:
subset_sample_array[:]=1001
subset_sample_array  

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

# two-dimensional array

In [ ]:
import numpy as np 

In [67]:
sample_matrix=np.array(([50,29,46,6],[56,63,47,9],[37,38,29,20]))
sample_matrix

array([[50, 29, 46,  6],
       [56, 63, 47,  9],
       [37, 38, 29, 20]])

In [68]:
sample_matrix[0][3]

6

In [71]:
sample_matrix [2,:]

array([37, 38, 29, 20])

In [73]:
sample_matrix[2]

array([37, 38, 29, 20])

In [74]:
sample_matrix[:,(3,2)]

array([[ 6, 46],
       [ 9, 47],
       [20, 29]])

# selection techniques

In [76]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [77]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [78]:
np.exp(sample_array) #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [79]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [80]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [81]:
np.max(sample_array)

19

In [83]:
np.min(sample_array)

1

In [84]:
np.argmax(sample_array)

18

In [86]:
np.argmin(sample_array)

0

In [85]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [87]:
np.std(sample_array)

5.477225575051661

In [88]:
np.var(sample_array)

30.0

In [89]:
np.mean(sample_array)

10.0

In [90]:
array=np.random.randn(3,5)
array

array([[-0.38775793,  1.23980764, -1.50837629, -0.02184443, -1.14045287],
       [-0.96442574, -0.55070944,  0.12031127,  0.80002695,  0.51431216],
       [-1.09279253,  0.52690803,  0.72295714,  2.20508557,  0.14049569]])

In [92]:
np.round(array,decimals=2)

array([[-0.39,  1.24, -1.51, -0.02, -1.14],
       [-0.96, -0.55,  0.12,  0.8 ,  0.51],
       [-1.09,  0.53,  0.72,  2.21,  0.14]])

In [94]:
sports= np.array(['ko-ko','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'ko-ko'], dtype='<U7')